services:
  app:
    networks:
      - laravel-network
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP:-1000}"
        WWWUSER: "${WWWUSER:-1000}"
    image: classroom-laravel-app
    container_name: app
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/home/app/ftp
      - ./public:/home/app/ftp/www
      - ./backups:/home/backupuser/ftp/fitxers
      - ./test_envs:/home/tests/ftp
      - ./logs/apache:/home/app/logs
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  ftp:
    networks:
      - laravel-network
    image: delfer/alpine-ftp-server:latest
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30050:30000-30050"
    volumes:
      - ./public:/home/app/ftp/www
      - ./backups:/home/backupuser/ftp/fitxers
      - ./test_envs:/home/tests/ftp
      - ./docker/vsftpd.conf:/etc/vsftpd/vsftpd.conf:ro
    environment:
      # format: name|password|home|uid|gid
      - USERS=app|passapp|/home/app/ftp/www|1000|1000 backupuser|passbackup|/home/backupuser/ftp/fitxers|1001|1001 tests|passtests|/home/tests/ftp|1002|1000 alumne1|pass1|/home/tests/ftp/alumne1/www|1003|1000 alumne2|pass2|/home/tests/ftp/alumne2/www|1004|1000 alumne3|pass3|/home/tests/ftp/alumne3/www|1005|1000
      - ADDRESS=localhost
      - MIN_PORT=30000
      - MAX_PORT=30050
    restart: always

  db:
    networks:
      - laravel-network
    image: mysql:8.4
    container_name: db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      retries: 3
      timeout: 5s
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    networks:
      - laravel-network
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  phpmyadmin:
    networks:
      - laravel-network
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: laravel
      PMA_PASSWORD: laravel
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:

networks:
  laravel-network:
    driver: bridge
