name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'frontend/**'
      - 'README.md'
      - '.gitignore'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, mysql, bcmath, gd

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Prepare .env for tests
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
        run: php artisan test

deploy:
    needs: tests
    runs-on: self-hosted # <--- ARA FEM SERVIR EL TEU PUNTET VERD!
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Production
        run: |
          cd ${{ secrets.PROD_PATH }}
          git pull origin main
          COMPOSE_PROFILES=app docker compose up -d --build app
          docker exec app php artisan key:generate --force
          docker exec app php artisan migrate --force
          docker exec app php artisan config:cache
          docker exec app php artisan route:cache
          docker exec app php artisan view:cache
